import { StyleSheet } from "react-native";

import { colors } from "./colors";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  appShell: { flex: 1, backgroundColor: colors.background },
  header: {
    height: 64,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.outline,
    backgroundColor: "rgba(11,19,38,0.94)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between"
  },
  brand: { flexDirection: "row", alignItems: "center", gap: 10 },
  logoMark: {
    width: 34,
    height: 34,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(208,188,255,0.35)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(208,188,255,0.12)"
  },
  logoText: { color: colors.primary, fontSize: 24, fontWeight: "800" },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 12 },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.04)"
  },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.primaryContainer,
    alignItems: "center",
    justifyContent: "center"
  },
  avatarText: { color: colors.onPrimary, fontWeight: "800", fontSize: 12 },
  content: { flex: 1 },
  screenContent: { padding: 16, paddingBottom: 116, gap: 18 },
  searchPanel: {
    minHeight: 58,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.outline,
    backgroundColor: "rgba(23,31,51,0.78)",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    gap: 12
  },
  searchInput: { flex: 1, color: colors.text, fontSize: 16 },
  aiStatus: { flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 4 },
  pulseAnchor: { width: 32, height: 32, alignItems: "center", justifyContent: "center" },
  pulseRing: { position: "absolute", width: 32, height: 32, borderRadius: 16, backgroundColor: colors.primary },
  pulseDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.primary },
  overline: { color: colors.muted, fontSize: 11, fontWeight: "800", letterSpacing: 1, textTransform: "uppercase" },
  overlinePrimary: { color: colors.primary, fontSize: 11, fontWeight: "800", letterSpacing: 1, textTransform: "uppercase" },
  statusLine: { height: 1, flex: 1, backgroundColor: "rgba(208,188,255,0.26)" },
  titleRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  sectionTitleText: { color: colors.text, fontSize: 22, fontWeight: "800" },
  chipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  chip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(208,188,255,0.2)",
    backgroundColor: "rgba(23,31,51,0.7)",
    paddingHorizontal: 16,
    paddingVertical: 10
  },
  chipText: { color: colors.muted, fontSize: 13, fontWeight: "700" },
  sectionHeader: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: 12 },
  bodyMuted: { color: colors.muted, fontSize: 13, lineHeight: 19 },
  linkText: { color: colors.primary, fontSize: 13, fontWeight: "800" },
  horizontalList: { gap: 14, paddingRight: 16 },
  screenshotCard: {
    width: 286,
    borderRadius: 18,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.outline,
    backgroundColor: "rgba(23,31,51,0.78)"
  },
  compactScreenshot: { width: 230 },
  previewGradient: { height: 164, padding: 18, justifyContent: "space-between" },
  previewImage: { height: 164, width: "100%", backgroundColor: colors.surfaceHigh },
  previewTopLine: { height: 5, width: "42%", borderRadius: 99, backgroundColor: "rgba(255,255,255,0.58)" },
  previewRows: { gap: 8 },
  previewRow: { height: 8, borderRadius: 99, backgroundColor: "rgba(255,255,255,0.24)" },
  screenshotFooter: { minHeight: 66, padding: 14, flexDirection: "row", alignItems: "center", gap: 12 },
  flexOne: { flex: 1 },
  cardTitle: { color: colors.text, fontSize: 16, fontWeight: "800" },
  cardBody: { color: colors.text, fontSize: 15, lineHeight: 22 },
  statGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  metricCard: {
    flexGrow: 1,
    flexBasis: "46%",
    minHeight: 104,
    borderRadius: 16,
    borderWidth: 1,
    borderLeftWidth: 3,
    borderColor: colors.outline,
    backgroundColor: "rgba(23,31,51,0.78)",
    padding: 16,
    justifyContent: "center"
  },
  metricLabel: { color: colors.muted, fontSize: 11, fontWeight: "800", textTransform: "uppercase" },
  metricValue: { fontSize: 24, fontWeight: "900", marginTop: 6 },
  askPanel: {
    minHeight: 54,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(208,188,255,0.22)",
    backgroundColor: "rgba(45,52,73,0.52)",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    gap: 10
  },
  askText: { flex: 1, color: colors.muted, fontSize: 15, fontWeight: "700" },
  chatShell: { flex: 1, paddingHorizontal: 16, paddingBottom: 92 },
  chatContent: { paddingTop: 16, paddingBottom: 88, gap: 16 },
  datePill: {
    alignSelf: "center",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.outline,
    paddingHorizontal: 14,
    paddingVertical: 6,
    backgroundColor: "rgba(23,31,51,0.72)"
  },
  messageRow: { maxWidth: "88%", flexDirection: "row", gap: 10, alignItems: "flex-start" },
  userMessageRow: { alignSelf: "flex-end", flexDirection: "row-reverse" },
  messageIcon: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center" },
  botIcon: { backgroundColor: "rgba(208,188,255,0.12)", borderWidth: 1, borderColor: "rgba(208,188,255,0.25)" },
  userIcon: { backgroundColor: "rgba(45,52,73,0.7)", borderWidth: 1, borderColor: colors.outline },
  messageBubble: { borderRadius: 18, padding: 14, borderWidth: 1 },
  aiBubble: { borderTopLeftRadius: 5, borderColor: colors.outline, backgroundColor: "rgba(23,31,51,0.78)" },
  userBubble: { borderTopRightRadius: 5, borderColor: "transparent", backgroundColor: colors.primaryContainer },
  messageText: { color: colors.text, fontSize: 15, lineHeight: 22 },
  userMessageText: { color: colors.onPrimary, fontWeight: "700" },
  typingRow: { flexDirection: "row", gap: 10, alignItems: "center" },
  typingBubble: {
    borderRadius: 18,
    borderTopLeftRadius: 5,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "rgba(23,31,51,0.78)",
    flexDirection: "row",
    gap: 5
  },
  typingDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: colors.primary },
  chatComposer: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 94,
    minHeight: 56,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(208,188,255,0.22)",
    backgroundColor: colors.surface,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    gap: 10
  },
  composerInput: { flex: 1, color: colors.text, fontSize: 15 },
  sendButton: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center", backgroundColor: colors.primary },
  pageIntro: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 14 },
  pageTitle: { color: colors.text, fontSize: 32, lineHeight: 38, fontWeight: "900" },
  primaryButton: {
    height: 44,
    borderRadius: 14,
    paddingHorizontal: 14,
    backgroundColor: colors.primary,
    flexDirection: "row",
    alignItems: "center",
    gap: 7
  },
  primaryButtonText: { color: colors.onPrimary, fontWeight: "900" },
  suggestionCard: { borderRadius: 18, borderWidth: 1, borderColor: colors.outline, backgroundColor: "rgba(23,31,51,0.78)", padding: 18, gap: 14 },
  suggestionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  badge: {
    alignSelf: "flex-start",
    overflow: "hidden",
    borderRadius: 999,
    color: colors.secondary,
    borderWidth: 1,
    borderColor: "rgba(76,215,246,0.28)",
    backgroundColor: "rgba(76,215,246,0.1)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: "900"
  },
  buttonRow: { flexDirection: "row", gap: 10 },
  secondaryButton: { borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, backgroundColor: colors.secondary },
  secondaryButtonText: { color: colors.onSecondary, fontWeight: "900" },
  subtleButton: {
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: colors.outline
  },
  subtleButtonText: { color: colors.text, fontWeight: "800" },
  collectionGrid: { flexDirection: "row", flexWrap: "wrap", gap: 14 },
  collectionItem: { width: "47%", gap: 10 },
  collectionFolder: {
    aspectRatio: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.outline,
    backgroundColor: "rgba(23,31,51,0.78)",
    alignItems: "center",
    justifyContent: "center",
    gap: 12
  },
  collectionName: { color: colors.text, textAlign: "center", fontSize: 16, fontWeight: "800" },
  heroMetric: {
    minHeight: 290,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.outline,
    backgroundColor: "rgba(23,31,51,0.78)",
    padding: 18,
    justifyContent: "space-between"
  },
  heroMetricHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  bigNumber: { color: colors.primary, fontSize: 70, lineHeight: 76, fontWeight: "900" },
  barChart: { height: 86, flexDirection: "row", alignItems: "flex-end", gap: 8 },
  chartBar: { flex: 1, borderTopLeftRadius: 9, borderTopRightRadius: 9, backgroundColor: colors.primaryContainer },
  efficiencyCard: { borderRadius: 18, borderWidth: 1, borderColor: colors.outline, backgroundColor: "rgba(23,31,51,0.78)", padding: 18, gap: 18 },
  efficiencyRow: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
    paddingBottom: 14,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 14
  },
  efficiencyLabel: { fontSize: 16, fontWeight: "900" },
  efficiencyValue: { color: colors.text, fontSize: 24, fontWeight: "900" },
  activeCore: {
    minHeight: 130,
    borderRadius: 65,
    borderWidth: 1,
    borderColor: "rgba(208,188,255,0.25)",
    backgroundColor: "rgba(45,52,73,0.34)",
    alignItems: "center",
    justifyContent: "center",
    gap: 10
  },
  bottomNav: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 12,
    minHeight: 70,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.outline,
    backgroundColor: "rgba(23,31,51,0.96)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 8
  },
  navItem: { minWidth: 68, minHeight: 48, borderRadius: 22, alignItems: "center", justifyContent: "center", gap: 3, paddingHorizontal: 8 },
  activeNavItem: { backgroundColor: colors.primaryContainer },
  navLabel: { color: colors.muted, fontSize: 10, fontWeight: "900" },
  activeNavLabel: { color: colors.onPrimary }
});
